### ISSUE TITLE
Savon 2.3.0 causes "Requested value 'APIObject' was not found." error

### ISSUE THREAD

**Issue by bbakersmith** [salesforce-marketingcloud/FuelSDK-Ruby#6]
Having switched to the Dot9Refactor branch, I'm still getting the error:

"Requested value 'APIObject' was not found."

This is the same error I got when trying to send a post request to a data extension using the master branch, and it is caused by the same test re-implemented using your Dot9Refactor branch.

Can you please do a proper test of the DataExtension post method against an actual live Exact Target account? Since the post test is the only one of my suite that's failing (all the rest are get) I'm still inclined to think that this is a bug with the FuelSDK-Ruby library. But I'd be happy to find out otherwise, that'd be easier to fix!

**Comment by mikepcoke** [comment]
I am getting this same issue trying to create a new list.  When I installed savon in my Gemfile it installed 2.11.1 by default.  I also tried just installing savon 2.2 on the command line (after removing 2.11.1)

But I still get the same error about APIObject not found.

@body=
  {:create_response=>
    {:results=>
      {:status_code=>"Error", :status_message=>"Requested value 'APIObject' was not found.", :ordinal_id=>"0", :new_id=>"0", :object=>{:partner_key=>nil, :object_id=>nil}},
     :request_id=>"ff4d2256-dc36-4fb3-a6a2-7ab05b3ef494",
     :overall_status=>"Error",
     :@xmlns=>"http://exacttarget.com/wsdl/partnerAPI"}},


Not sure if there is something else obviously potentially going on or if this might be Savon related?

**Comment by c4collins** [comment]
Hey there,

I don't know if this is still an issue, but I came across this problem and then fixed it today in my own implementation of the ExactTarget SOAP API (in Python, mind you).

**The meaning of this error:**
When you submit a request to ET's SOAP API you have to declare the type of the object and make sure it matches the expected format.  In most cases, if you screw up that format, ET will be very explicit about what the expected object was (i.e. "Requested value 'RetrieveRequest' was not found.") , but there are a few methods that aren't as strict and will accept multiple object types (Delete is the one that caught me out today), and in that case it gives the generic error for the superclass APIObject - "Requested value 'APIObject' was not found."

**The solution:**
I have no idea where this would be cropping up in the SDK, because I'm building my own, but basically I just had to set up a switch to determine the type of the object (usually just by passing in an object_type value) and then ensure that the correct object is created and sent to the SDK for each different ObjectType.

**Comment by xjunior** [comment]
I had to deal with these guys on my previous job. It was horrible. I hope I never have to deal with ExactTarget or it's crappy and old SOAP API, along with their horrible support.

**Comment by dopstar** [comment]
@c4collins are you perhaps planning to share your own implementation in future?
